### ISSUE TITLE
building 1.7.10 branch

### ISSUE THREAD

**Issue by k1r0s** [Sinhika/Netherrocks#11]
Hello, 

So i've just downloaded the source and tried to run it. But I have a problem choosing simplecore dependency version. Though using this one https://www.curseforge.com/minecraft/mc-mods/simplecore-api/files/2293235 im able to compile the source but not able to gradle runClient:

```
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77655_b(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:480)
	at net.minecraft.client.Minecraft.run(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77655_b(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at alexndr.api.content.items.SimpleItem.setUnlocalizedName(SimpleItem.java:91)
	at alexndr.plugins.Netherrocks.Content.doItems(Content.java:101)
	at alexndr.plugins.Netherrocks.Content.preInitialize(Content.java:33)
	at alexndr.plugins.Netherrocks.Netherrocks.PreInit(Netherrocks.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at ...```

So im indeed picking the wrong one (as is infered by the upload date too)

Thanks!

**Comment by Sinhika** [comment]
I am no longer supporting code previous to 1.14.
