### ISSUE TITLE
Harvesting Crops on 1.12.2 Crash

### ISSUE THREAD

**Issue by UnpeelableBanana** [Sinhika/Netherrocks#22]
When I right click on wheat and other crops my game crashes with netherrocks installed. Normally, I wouldn't report a 1.12.2 issue, but this seems like a major bug rather than a small inconvenience. The issue disappears when I no longer have the mod in my mods folder. I am using version Netherrocks 1.7.1.2 The following error is displayed when I crash: 

java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1640)
	at alexndr.plugins.netherrocks.helpers.FyriteHandler.onHarvestDrops(FyriteHandler.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2517_FyriteHandler_onHarvestDrops_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
	at vazkii.quark.tweaks.feature.RightClickHarvest.replant(RightClickHarvest.java:134)
	at vazkii.quark.tweaks.feature.RightClickHarvest.onCropClick(RightClickHarvest.java:184)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1194_RightClickHarvest_onCropClick_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Handeril** [comment]
This bug also effects Quark: RoTN Edition, as a note.
